version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres-database-container
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_pwd
      POSTGRES_DB: automotive_parts_organizational_system
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
